static func get_data() -> Array:
    return [
        PlayerData.new(1, Vector2i(2, 12)),
        PlayerData.new(1, Vector2i(4, 12)),
        PlayerData.new(1, Vector2i(6, 12)),
        OreData.new(2, Vector2i(4, 6)),
        StoneData.new(Vector2i(4, 9)),
        OreData.new(8, Vector2i(5, 0)),
        StoneData.new(Vector2i(3, 7)),
        OreData.new(1, Vector2i(4, 0)),
        StoneData.new(Vector2i(4, 3)),
        OreData.new(1, Vector2i(5, 3)),
        OreData.new(5, Vector2i(7, 3)),
        StoneData.new(Vector2i(7, 6)),
        OreData.new(1, Vector2i(7, 9)),
        OreData.new(5, Vector2i(6, 0)),
        StoneData.new(Vector2i(6, 3)),
        OreData.new(7, Vector2i(7, 0)),
        OreData.new(8, Vector2i(0, 8)),
        OreData.new(4, Vector2i(0, 9)),
        OreData.new(4, Vector2i(1, 0)),
        StoneData.new(Vector2i(0, 0)),
        StoneData.new(Vector2i(0, 1)),
        OreData.new(2, Vector2i(0, 3)),
        OreData.new(7, Vector2i(1, 9)),
        OreData.new(2, Vector2i(3, 2)),
        OreData.new(7, Vector2i(3, 4)),
        StoneData.new(Vector2i(3, 6)),
        OreData.new(9, Vector2i(2, 0)),
        OreData.new(9, Vector2i(3, 0)),
        OreData.new(6, Vector2i(3, 1))
    ]
