static func get_data() -> Array:
    return [
        PlayerData.new(1, Vector2i(2, 12)),
        PlayerData.new(1, Vector2i(4, 12)),
        PlayerData.new(1, Vector2i(6, 12)),
        OreData.new(8, Vector2i(3, 6)),
        OreData.new(3, Vector2i(3, 7)),
        OreData.new(2, Vector2i(3, 5)),
        OreData.new(4, Vector2i(2, 7)),
        StoneData.new(Vector2i(3, 1)),
        OreData.new(5, Vector2i(5, 4)),
        OreData.new(8, Vector2i(7, 4)),
        StoneData.new(Vector2i(7, 5)),
        StoneData.new(Vector2i(6, 5)),
        StoneData.new(Vector2i(5, 5)),
        OreData.new(5, Vector2i(6, 4)),
        OreData.new(1, Vector2i(2, 6)),
        StoneData.new(Vector2i(1, 2)),
        OreData.new(3, Vector2i(1, 3)),
        OreData.new(3, Vector2i(0, 4)),
        OreData.new(8, Vector2i(0, 2)),
        OreData.new(4, Vector2i(0, 3)),
        OreData.new(7, Vector2i(1, 4)),
        OreData.new(1, Vector2i(2, 3)),
        StoneData.new(Vector2i(2, 4)),
        OreData.new(3, Vector2i(2, 2)),
        OreData.new(4, Vector2i(1, 5)),
        OreData.new(2, Vector2i(1, 6))
    ]
