static func get_data() -> Array:
    return [
        PlayerData.new(1, Vector2i(1, 12)),
        PlayerData.new(1, Vector2i(3, 12)),
        PlayerData.new(1, Vector2i(4, 12)),
        PlayerData.new(1, Vector2i(6, 12)),
        OreData.new(13, Vector2i(5, 6)),
        OreData.new(3, Vector2i(5, 5)),
        OreData.new(15, Vector2i(5, 4)),
        OreData.new(10, Vector2i(5, 9)),
        OreData.new(4, Vector2i(5, 8)),
        StoneData.new(Vector2i(5, 7)),
        StoneData.new(Vector2i(5, 3)),
        StoneData.new(Vector2i(4, 9)),
        OreData.new(14, Vector2i(4, 8)),
        OreData.new(3, Vector2i(4, 7)),
        StoneData.new(Vector2i(5, 2)),
        OreData.new(5, Vector2i(5, 1)),
        StoneData.new(Vector2i(5, 0)),
        StoneData.new(Vector2i(7, 2)),
        OreData.new(5, Vector2i(7, 1)),
        OreData.new(8, Vector2i(7, 0)),
        StoneData.new(Vector2i(7, 6)),
        OreData.new(5, Vector2i(7, 5)),
        StoneData.new(Vector2i(7, 3)),
        OreData.new(14, Vector2i(6, 8)),
        StoneData.new(Vector2i(6, 4)),
        OreData.new(1, Vector2i(6, 3)),
        StoneData.new(Vector2i(6, 2)),
        OreData.new(7, Vector2i(6, 7)),
        OreData.new(11, Vector2i(6, 6)),
        OreData.new(2, Vector2i(6, 5)),
        StoneData.new(Vector2i(1, 8)),
        OreData.new(7, Vector2i(1, 5)),
        StoneData.new(Vector2i(1, 4)),
        StoneData.new(Vector2i(2, 1)),
        OreData.new(6, Vector2i(2, 0)),
        StoneData.new(Vector2i(1, 9)),
        StoneData.new(Vector2i(1, 3)),
        StoneData.new(Vector2i(0, 4)),
        OreData.new(1, Vector2i(0, 3)),
        OreData.new(7, Vector2i(0, 1)),
        StoneData.new(Vector2i(1, 1)),
        OreData.new(4, Vector2i(1, 0)),
        StoneData.new(Vector2i(0, 5)),
        StoneData.new(Vector2i(4, 1)),
        OreData.new(4, Vector2i(3, 8)),
        OreData.new(2, Vector2i(3, 5)),
        OreData.new(14, Vector2i(4, 5)),
        OreData.new(9, Vector2i(4, 3)),
        OreData.new(15, Vector2i(4, 2)),
        OreData.new(2, Vector2i(3, 4)),
        OreData.new(10, Vector2i(2, 4)),
        StoneData.new(Vector2i(2, 3)),
        StoneData.new(Vector2i(2, 2)),
        OreData.new(12, Vector2i(3, 3)),
        OreData.new(14, Vector2i(3, 2)),
        OreData.new(7, Vector2i(2, 8))
    ]
