static func get_data() -> Array:
    return [
        PlayerData.new(1, Vector2i(2, 12)),
        PlayerData.new(1, Vector2i(5, 12)),
        StoneData.new(Vector2i(5, 3)),
        StoneData.new(Vector2i(5, 1)),
        OreData.new(5, Vector2i(5, 5)),
        OreData.new(6, Vector2i(5, 9)),
        OreData.new(6, Vector2i(5, 7)),
        StoneData.new(Vector2i(4, 3)),
        StoneData.new(Vector2i(4, 2)),
        OreData.new(1, Vector2i(4, 6)),
        OreData.new(2, Vector2i(4, 9)),
        OreData.new(3, Vector2i(4, 8)),
        OreData.new(4, Vector2i(6, 1)),
        OreData.new(5, Vector2i(7, 5)),
        OreData.new(6, Vector2i(7, 3)),
        OreData.new(5, Vector2i(7, 7)),
        StoneData.new(Vector2i(7, 9)),
        OreData.new(4, Vector2i(7, 8)),
        OreData.new(5, Vector2i(6, 5)),
        OreData.new(1, Vector2i(6, 4)),
        OreData.new(4, Vector2i(6, 6)),
        StoneData.new(Vector2i(7, 1)),
        OreData.new(1, Vector2i(6, 8)),
        OreData.new(3, Vector2i(4, 0)),
        StoneData.new(Vector2i(1, 5)),
        OreData.new(3, Vector2i(1, 3)),
        StoneData.new(Vector2i(1, 7)),
        OreData.new(3, Vector2i(2, 0)),
        OreData.new(4, Vector2i(1, 9)),
        OreData.new(2, Vector2i(0, 4)),
        OreData.new(4, Vector2i(0, 2)),
        OreData.new(3, Vector2i(0, 5)),
        OreData.new(3, Vector2i(1, 1)),
        OreData.new(4, Vector2i(0, 6)),
        OreData.new(5, Vector2i(2, 2)),
        OreData.new(2, Vector2i(3, 1)),
        OreData.new(5, Vector2i(3, 0)),
        OreData.new(2, Vector2i(3, 3)),
        OreData.new(2, Vector2i(3, 7)),
        OreData.new(5, Vector2i(3, 5)),
        OreData.new(4, Vector2i(2, 4)),
        OreData.new(2, Vector2i(2, 3)),
        OreData.new(2, Vector2i(2, 5)),
        StoneData.new(Vector2i(2, 8)),
        OreData.new(2, Vector2i(2, 6))
    ]
