static func get_data() -> Array:
    return [
        PlayerData.new(1, Vector2i(2, 12)),
        PlayerData.new(1, Vector2i(5, 12)),
        OreData.new(3, Vector2i(5, 1)),
        StoneData.new(Vector2i(5, 3)),
        OreData.new(4, Vector2i(5, 6)),
        StoneData.new(Vector2i(4, 3)),
        OreData.new(4, Vector2i(4, 6)),
        OreData.new(2, Vector2i(4, 8)),
        StoneData.new(Vector2i(5, 8)),
        OreData.new(3, Vector2i(6, 8)),
        OreData.new(4, Vector2i(7, 1)),
        OreData.new(1, Vector2i(7, 8)),
        OreData.new(4, Vector2i(6, 1)),
        OreData.new(3, Vector2i(6, 3)),
        OreData.new(3, Vector2i(6, 6)),
        OreData.new(2, Vector2i(4, 1)),
        OreData.new(3, Vector2i(1, 1)),
        OreData.new(1, Vector2i(1, 3)),
        OreData.new(1, Vector2i(1, 6)),
        OreData.new(1, Vector2i(0, 3)),
        OreData.new(1, Vector2i(0, 6)),
        StoneData.new(Vector2i(0, 8)),
        OreData.new(4, Vector2i(1, 8)),
        OreData.new(2, Vector2i(3, 1)),
        OreData.new(2, Vector2i(3, 6)),
        OreData.new(1, Vector2i(3, 8)),
        OreData.new(2, Vector2i(2, 1)),
        OreData.new(3, Vector2i(2, 6)),
        OreData.new(2, Vector2i(2, 8))
    ]
